// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1me7yztdyz4173epMNcYkmT9BK_HN_Nw',
    appId: '1:180725745491:web:c79c60060cd2b1acc743a6',
    messagingSenderId: '180725745491',
    projectId: 'recurrent-checklist',
    authDomain: 'recurrent-checklist.firebaseapp.com',
    storageBucket: 'recurrent-checklist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCksGkPC6vBCdWT2y_zfyEi4Ftz5s01-0w',
    appId: '1:180725745491:android:507c310e8d58a91fc743a6',
    messagingSenderId: '180725745491',
    projectId: 'recurrent-checklist',
    storageBucket: 'recurrent-checklist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIdCXmDWnBXJBRfSIcXcrqr5Nmf-6bPg',
    appId: '1:180725745491:ios:18f38349b84e9da1c743a6',
    messagingSenderId: '180725745491',
    projectId: 'recurrent-checklist',
    storageBucket: 'recurrent-checklist.firebasestorage.app',
    iosBundleId: 'com.example.recurrentChecklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqIdCXmDWnBXJBRfSIcXcrqr5Nmf-6bPg',
    appId: '1:180725745491:ios:18f38349b84e9da1c743a6',
    messagingSenderId: '180725745491',
    projectId: 'recurrent-checklist',
    storageBucket: 'recurrent-checklist.firebasestorage.app',
    iosBundleId: 'com.example.recurrentChecklist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1me7yztdyz4173epMNcYkmT9BK_HN_Nw',
    appId: '1:180725745491:web:72e50547d68d809cc743a6',
    messagingSenderId: '180725745491',
    projectId: 'recurrent-checklist',
    authDomain: 'recurrent-checklist.firebaseapp.com',
    storageBucket: 'recurrent-checklist.firebasestorage.app',
  );
}
